In [2]:
import numpy as np
print(np.__version__)

1.26.4


**Exercice 1:**

*Array Creation and Manipulation*

* Instructions

*Create a 1D NumPy array containing numbers from 0 to 9.*

In [3]:
table_1= np.arange(10)
print(table_1)

[0 1 2 3 4 5 6 7 8 9]


**Exercice 2:**

*Type Conversion and Array Operations*

* Instructions

*Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.*

In [4]:
table_2= np.array([3.14, 2.17, 0, 1, 2]).astype(int)
print(table_2)

[3 2 0 1 2]


**Exercice 3:**

*Working with Multi-Dimensional Arrays*

* Instructions

*Create a 3x3 NumPy array with values ranging from 1 to 9.*

In [7]:
table_3 = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
table_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Exercice 4:**

*Creating Multi-Dimensional Array with Random Numbers*

* Instructions

*Create a 2D NumPy array of shape (4, 5) filled with random numbers.*

In [12]:
import random
table_4 = np.random.rand(4, 5)
table_4 = np.round(table_4, 2)
table_4

array([[0.98, 0.33, 0.01, 0.29, 0.6 ],
       [0.9 , 0.79, 0.19, 0.81, 0.48],
       [0.22, 0.29, 0.71, 0.4 , 0.65],
       [0.21, 0.24, 0.32, 0.26, 0.75]])

**Exercice 5:**

*Indexing Arrays*

* Instructions

*Select the second row from a given 2D NumPy array.*

In [14]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array = array[1]
array

array([20, 21, 22, 23, 24])

**Exercice 6:**

*Reversing elements*

* Instructions

*Reverse the order of elements in a given 1D NumPy array (first element becomes last).*

In [15]:
table_1_inversed = table_1[::-1]
table_1_inversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Exercice 7:**

*Reversing elements*

* Instructions

*Reverse the order of elements in a given 1D NumPy array (first element becomes last).*

In [16]:
table_7 = np.eye(4, dtype= 'float')
table_7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Exercice 8:**

*Simple Aggregate Funcs*

* Instructions

*Find the sum and average of a given 1D array.*

In [20]:
sum_1 = table_1.sum()
mean_1 = table_1.mean()
print(f"The sum of the array table_1 is {sum_1}")
print(f"The mean of the array table_1 is {mean_1}")

The sum of the array table_1 is 45
The mean of the array table_1 is 4.5


**Exercice 9 :**

*Create Array and Change its Structure*

* Instructions

*Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.*

In [21]:
table_9 = np.arange(1, 21)
table_9 = table_9.reshape(4, 5)
table_9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

**Exercice 10 :**

*Conditional Selection of Values*

* Instructions

*Extract all odd numbers from a given NumPy array.*

In [22]:
table_10 = table_9[table_9 % 2 != 0]
table_10

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])